# Generated by Django 4.2.16 on 2026-06-11 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_file', models.FileField(blank=True, null=True, upload_to='joins/%Y/%m/')),
                ('ref_filename', models.CharField(blank=True, max_length=255)),
                ('ref_sheet', models.CharField(blank=True, max_length=100)),
                ('join_type', models.CharField(choices=[('LEFT', 'LEFT JOIN'), ('INNER', 'INNER JOIN'), ('FULL', 'FULL OUTER JOIN')], default='LEFT', max_length=10)),
                ('left_key', models.CharField(max_length=100)),
                ('right_key', models.CharField(max_length=100)),
                ('columns_to_add', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('ERROR', 'Erreur')], default='PENDING', max_length=10)),
                ('result_rows', models.IntegerField(default=0)),
                ('result_columns', models.IntegerField(default=0)),
                ('match_rate', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins_as_main', to='imports.importedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
