# Generated by Django 4.2.16 on 2026-06-11 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('survey_type', models.CharField(max_length=100)),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('version_mode', models.CharField(choices=[('NEW', 'Nouvelle version'), ('REPLACE', 'Remplacement'), ('CONCAT', 'Concaténation')], default='NEW', max_length=10)),
                ('rows_processed', models.IntegerField(default=0)),
                ('columns_count', models.IntegerField(default=0)),
                ('join_applied', models.BooleanField(default=False)),
                ('output_file_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.importedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMPORT', 'Import fichier'), ('CLEAN', 'Nettoyage'), ('JOIN', 'Jointure'), ('EXPORT', 'Export'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE_USER', 'Création utilisateur'), ('DELETE', 'Suppression'), ('TEMPLATE_SAVE', 'Sauvegarde modèle')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.importedfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
