# Generated by Django 4.2.16 on 2026-06-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingreport',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processingreport',
            name='nps_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
