# Generated by Django 4.2.16 on 2026-06-11 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('survey_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column_mapping', models.JSONField(default=dict)),
                ('columns_to_drop', models.JSONField(default=list)),
                ('header_rows_to_skip', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploadé'), ('ANALYZING', 'Analyse en cours'), ('ANALYZED', 'Analysé'), ('CLEANING', 'Nettoyage en cours'), ('CLEANED', 'Nettoyé'), ('JOINED', 'Enrichi'), ('EXPORTED', 'Exporté'), ('ERROR', 'Erreur')], default='UPLOADED', max_length=20)),
                ('survey_type', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('total_rows', models.IntegerField(default=0)),
                ('total_columns', models.IntegerField(default=0)),
                ('detected_structure', models.JSONField(default=dict)),
                ('column_mapping', models.JSONField(default=dict)),
                ('columns_to_drop', models.JSONField(default=list)),
                ('header_rows_to_skip', models.IntegerField(default=2)),
                ('is_surveymonkey', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.surveytemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
