# Generated by Django 4.2.16 on 2026-06-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='column_order',
            field=models.JSONField(default=list),
        ),
    ]
